### ISSUE TITLE
subsite ignores language

### ISSUE THREAD

**Issue by cloph** [silverstripe/silverstripe-subsites#83]
in ss 3.1, configure two subsites, one in english, one in german. your site's default lang is english.

Despite having configured the german subsite to use "German" as language, the created HTML (the simple theme uses the field $ContentLocale) is set to english (en-US)

**Comment by gregsmirnov** [comment]
I use this extension to SiteTree.
```yml
---
Name: mysubsites
Only:
  moduleexists: subsites
---
SiteTree:
  extensions:
    - SubsitesLanguage
```
```php
class SubsitesLanguage extends Extension
{
	public function contentcontrollerInit() {
		$subsite = Subsite::currentSubsite();
		if (i18n::validate_locale($subsite->Language)) {
			i18n::set_locale($subsite->Language);
		}
	}
}
```
